
services:
  app:
    image: node:18
    command: "npm run dev"
    working_dir: /app
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
    environment:
      - DB_HOST=db
  
  db:
    image: postgres:latest
    container_name: db-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: issues
    ports:
      - "8888:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
